### ISSUE TITLE
[bug] (Ubuntu 18.04) make command fails

### ISSUE THREAD

**Issue by PicoJr** [google/fscrypt#109]
`make` command fails with:

```
go build --ldflags '-s -w -X "main.version=v0.2.4-13-g0294624" -X "main.buildTime=lundi 15 octobre 2018, 19:13:56 (UTC+0200)" -extldflags ""' -o bin/fscrypt ./cmd/fscrypt
# github.com/google/fscrypt/vendor/golang.org/x/sys/unix
vendor/golang.org/x/sys/unix/affinity_linux.go:13:7: const initializer _CPU_SETSIZE / _NCPUBITS is not a constant
vendor/golang.org/x/sys/unix/affinity_linux.go:13:20: undefined: _CPU_SETSIZE
vendor/golang.org/x/sys/unix/affinity_linux.go:13:35: undefined: _NCPUBITS
vendor/golang.org/x/sys/unix/affinity_linux.go:16:25: undefined: cpuMask
Makefile:88: recipe for target 'bin/fscrypt' failed
make: *** [bin/fscrypt] Error 2
```

* `libpam0g-dev` is installed (OS: `Ubuntu 18.04.1 LTS`)
* go version `go1.10.1 linux/amd64`
* make version `GNU Make 4.1`

commit 0294624efdef9b78e305453b740d380a64583324

Best regards,

PicoJr

**Comment by josephlr** [comment]
Looks like this is probobly caused by https://github.com/google/fscrypt/commit/0f451a722918f39fa07bd9337e4a14ca154b13ae, where we update the vendored dependencies.

We may just have to drop Go 1.10 support (which we'll have to do anyway in a few months), I will take a look to see if there's an easy way to keep support for more versions.

**Comment by PicoJr** [comment]
@josephlr Thanks for your message, I updated my system, re-ran `go get` and it now works =)

You rock! Thanks!

**Comment by outusuke** [comment]
i have this error when running make on zorin os 15.1

go build --ldflags '-s -w -X "main.version=v0.2.5-31-g6821d90" -X "main.buildTime=dom dez 15 18:00:53 -03 2019" -extldflags ""' -o bin/fscrypt ./cmd/fscrypt
metadata/config.go:33:2: cannot find package "github.com/golang/protobuf/jsonpb" in any of:
	/usr/lib/go-1.10/src/github.com/golang/protobuf/jsonpb (from $GOROOT)
	/home/anonimo/go/src/github.com/golang/protobuf/jsonpb (from $GOPATH)
actions/policy.go:26:2: cannot find package "github.com/golang/protobuf/proto" in any of:
	/usr/lib/go-1.10/src/github.com/golang/protobuf/proto (from $GOROOT)
	/home/anonimo/go/src/github.com/golang/protobuf/proto (from $GOPATH)
util/errors.go:28:2: cannot find package "github.com/pkg/errors" in any of:
	/usr/lib/go-1.10/src/github.com/pkg/errors (from $GOROOT)
	/home/anonimo/go/src/github.com/pkg/errors (from $GOPATH)
cmd/fscrypt/commands.go:29:2: cannot find package "github.com/urfave/cli" in any of:
	/usr/lib/go-1.10/src/github.com/urfave/cli (from $GOROOT)
	/home/anonimo/go/src/github.com/urfave/cli (from $GOPATH)
crypto/crypto.go:43:2: cannot find package "golang.org/x/crypto/argon2" in any of:
	/usr/lib/go-1.10/src/golang.org/x/crypto/argon2 (from $GOROOT)
	/home/anonimo/go/src/golang.org/x/crypto/argon2 (from $GOPATH)
crypto/crypto.go:44:2: cannot find package "golang.org/x/crypto/hkdf" in any of:
	/usr/lib/go-1.10/src/golang.org/x/crypto/hkdf (from $GOROOT)
	/home/anonimo/go/src/golang.org/x/crypto/hkdf (from $GOPATH)
cmd/fscrypt/format.go:32:2: cannot find package "golang.org/x/crypto/ssh/terminal" in any of:
	/usr/lib/go-1.10/src/golang.org/x/crypto/ssh/terminal (from $GOROOT)
	/home/anonimo/go/src/golang.org/x/crypto/ssh/terminal (from $GOPATH)
metadata/constants.go:25:2: cannot find package "golang.org/x/sys/unix" in any of:
	/usr/lib/go-1.10/src/golang.org/x/sys/unix (from $GOROOT)
	/home/anonimo/go/src/golang.org/x/sys/unix (from $GOPATH)
Makefile:91: recipe for target 'bin/fscrypt' failed
make: *** [bin/fscrypt] Error 1
